// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetBookRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookRequest) Reset()         { *m = GetBookRequest{} }
func (m *GetBookRequest) String() string { return proto.CompactTextString(m) }
func (*GetBookRequest) ProtoMessage()    {}
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{0}
}

func (m *GetBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookRequest.Unmarshal(m, b)
}
func (m *GetBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookRequest.Marshal(b, m, deterministic)
}
func (m *GetBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookRequest.Merge(m, src)
}
func (m *GetBookRequest) XXX_Size() int {
	return xxx_messageInfo_GetBookRequest.Size(m)
}
func (m *GetBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookRequest proto.InternalMessageInfo

func (m *GetBookRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetBookResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Summary              string   `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Image                string   `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookResponse) Reset()         { *m = GetBookResponse{} }
func (m *GetBookResponse) String() string { return proto.CompactTextString(m) }
func (*GetBookResponse) ProtoMessage()    {}
func (*GetBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{1}
}

func (m *GetBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookResponse.Unmarshal(m, b)
}
func (m *GetBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookResponse.Marshal(b, m, deterministic)
}
func (m *GetBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookResponse.Merge(m, src)
}
func (m *GetBookResponse) XXX_Size() int {
	return xxx_messageInfo_GetBookResponse.Size(m)
}
func (m *GetBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookResponse proto.InternalMessageInfo

func (m *GetBookResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetBookResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetBookResponse) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *GetBookResponse) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *GetBookResponse) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type SearchBookRequest struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchBookRequest) Reset()         { *m = SearchBookRequest{} }
func (m *SearchBookRequest) String() string { return proto.CompactTextString(m) }
func (*SearchBookRequest) ProtoMessage()    {}
func (*SearchBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{2}
}

func (m *SearchBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchBookRequest.Unmarshal(m, b)
}
func (m *SearchBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchBookRequest.Marshal(b, m, deterministic)
}
func (m *SearchBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchBookRequest.Merge(m, src)
}
func (m *SearchBookRequest) XXX_Size() int {
	return xxx_messageInfo_SearchBookRequest.Size(m)
}
func (m *SearchBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchBookRequest proto.InternalMessageInfo

func (m *SearchBookRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type SearchBookResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Summary              string   `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Image                string   `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchBookResponse) Reset()         { *m = SearchBookResponse{} }
func (m *SearchBookResponse) String() string { return proto.CompactTextString(m) }
func (*SearchBookResponse) ProtoMessage()    {}
func (*SearchBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{3}
}

func (m *SearchBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchBookResponse.Unmarshal(m, b)
}
func (m *SearchBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchBookResponse.Marshal(b, m, deterministic)
}
func (m *SearchBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchBookResponse.Merge(m, src)
}
func (m *SearchBookResponse) XXX_Size() int {
	return xxx_messageInfo_SearchBookResponse.Size(m)
}
func (m *SearchBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchBookResponse proto.InternalMessageInfo

func (m *SearchBookResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SearchBookResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SearchBookResponse) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *SearchBookResponse) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *SearchBookResponse) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func init() {
	proto.RegisterType((*GetBookRequest)(nil), "pb.GetBookRequest")
	proto.RegisterType((*GetBookResponse)(nil), "pb.GetBookResponse")
	proto.RegisterType((*SearchBookRequest)(nil), "pb.SearchBookRequest")
	proto.RegisterType((*SearchBookResponse)(nil), "pb.SearchBookResponse")
}

func init() { proto.RegisterFile("book.proto", fileDescriptor_1e89d0eaa98dc5d8) }

var fileDescriptor_1e89d0eaa98dc5d8 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x49, 0x68, 0x1a, 0xf5, 0x86, 0x22, 0x0e, 0xa8, 0xac, 0x4e, 0x91, 0xa7, 0x2e, 0x64,
	0x00, 0x56, 0x16, 0x16, 0xf6, 0xf0, 0x0b, 0x62, 0x7a, 0xa2, 0x56, 0x08, 0x67, 0x6c, 0x47, 0xa8,
	0x62, 0x40, 0xe2, 0x97, 0xa3, 0xd8, 0x0d, 0xb4, 0xe1, 0x07, 0x74, 0xfc, 0x9e, 0x9f, 0xcf, 0xcf,
	0xef, 0x00, 0x14, 0x73, 0x53, 0x1a, 0xcb, 0x9e, 0x31, 0x35, 0x4a, 0x16, 0x30, 0x7f, 0x24, 0xff,
	0xc0, 0xdc, 0x54, 0xf4, 0xde, 0x91, 0xf3, 0x38, 0x87, 0x54, 0xaf, 0x45, 0x52, 0x24, 0xab, 0xac,
	0x4a, 0xf5, 0x5a, 0x7e, 0xc1, 0xd9, 0xaf, 0xc3, 0x19, 0x7e, 0x73, 0x34, 0xb6, 0xe0, 0x25, 0x64,
	0x5e, 0xfb, 0x57, 0x12, 0x69, 0x91, 0xac, 0x66, 0x55, 0x04, 0x5c, 0xc0, 0xb4, 0xee, 0xfc, 0x86,
	0xad, 0x38, 0x0d, 0xf2, 0x8e, 0x50, 0x40, 0xee, 0xba, 0xb6, 0xad, 0xed, 0x56, 0x4c, 0xc2, 0xc1,
	0x80, 0xfd, 0x1c, 0xdd, 0xd6, 0x2f, 0x24, 0xb2, 0x38, 0x27, 0x80, 0xbc, 0x86, 0xf3, 0x27, 0xaa,
	0xed, 0xf3, 0x66, 0x3f, 0xa5, 0x80, 0xbc, 0xa1, 0xed, 0x07, 0xdb, 0x98, 0x63, 0x56, 0x0d, 0x28,
	0xbf, 0x13, 0xc0, 0x7d, 0xff, 0x31, 0x32, 0xdf, 0x7c, 0xc2, 0xa4, 0x7f, 0x1d, 0xef, 0x20, 0xdf,
	0x95, 0x87, 0x58, 0x1a, 0x55, 0x1e, 0x76, 0xbd, 0xbc, 0x38, 0xd0, 0x62, 0x52, 0x79, 0x82, 0xf7,
	0x00, 0x7f, 0x3f, 0xc0, 0xab, 0xde, 0xf4, 0xaf, 0x81, 0xe5, 0x62, 0x2c, 0x0f, 0xd7, 0xd5, 0x34,
	0xac, 0xf7, 0xf6, 0x27, 0x00, 0x00, 0xff, 0xff, 0x73, 0x70, 0x52, 0x78, 0xec, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookClient is the client API for Book service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookClient interface {
	GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*GetBookResponse, error)
	SearchBook(ctx context.Context, in *SearchBookRequest, opts ...grpc.CallOption) (*SearchBookResponse, error)
}

type bookClient struct {
	cc *grpc.ClientConn
}

func NewBookClient(cc *grpc.ClientConn) BookClient {
	return &bookClient{cc}
}

func (c *bookClient) GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*GetBookResponse, error) {
	out := new(GetBookResponse)
	err := c.cc.Invoke(ctx, "/pb.Book/GetBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) SearchBook(ctx context.Context, in *SearchBookRequest, opts ...grpc.CallOption) (*SearchBookResponse, error) {
	out := new(SearchBookResponse)
	err := c.cc.Invoke(ctx, "/pb.Book/SearchBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServer is the server API for Book service.
type BookServer interface {
	GetBook(context.Context, *GetBookRequest) (*GetBookResponse, error)
	SearchBook(context.Context, *SearchBookRequest) (*SearchBookResponse, error)
}

func RegisterBookServer(s *grpc.Server, srv BookServer) {
	s.RegisterService(&_Book_serviceDesc, srv)
}

func _Book_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Book/GetBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).GetBook(ctx, req.(*GetBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_SearchBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).SearchBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Book/SearchBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).SearchBook(ctx, req.(*SearchBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Book_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Book",
	HandlerType: (*BookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBook",
			Handler:    _Book_GetBook_Handler,
		},
		{
			MethodName: "SearchBook",
			Handler:    _Book_SearchBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book.proto",
}
